version: '3'
services:
  app:
    build: .
    image: commonfare_dev_rails_app
    container_name: commonfare_dev_rails_app
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # links app container to postgres container.
    # Containers for the linked service will be reachable at a hostname identical to the alias, or the service name if no alias was specified.
    # see https://docs.docker.com/compose/compose-file/#links
    links:
      - postgres
      - mailcatcher
    # These two allow debug with pry
    tty: true
    stdin_open: true
  mailcatcher:
    image: yappabe/mailcatcher
    container_name: commonfare_mailcatcher
    ports:
        - 1025:1025
        - 1080:1080
  postgres:
    image: postgres:9.6
    container_name: commonfare_pg
    ports:
      - "5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
