version: '2'
services:
  app:
    build: .
    image: commonfare_dev_rails_app
    container_name: commonfare_dev_rails_app
    restart: always
    command: >
      bash -c "
      rm -f /app/tmp/pids/development.pid;
      bundle exec whenever --update-crontab --set environment=development;
      cron && rails server -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/development.pid
      "
    volumes:
      - ~/tmp:/host_tmp
      - ~/tmp/commonshare-data:/commonshare-data
      - ~/tmp/dashboard-data:/dashboard-data
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    # links app container to postgres container.
    # Containers for the linked service will be reachable at a hostname identical to the alias, or the service name if no alias was specified.
    # see https://docs.docker.com/compose/compose-file/#links
    depends_on:
      - postgres
      - mailcatcher
      - webpack-dev-server
    env_file:
      - ./app_variables.env
    # These two allow debug with pry
    tty: true
    stdin_open: true
  webpack-dev-server:
    image: commonfare_dev_rails_app
    container_name: commonfare_dev_webpack
    restart: always
    command: bash -c "rm -rf /app/public/packs; ./bin/webpack-dev-server"
    ports:
      - "3035:3035"
    volumes:
      - ~/tmp:/host_tmp
      - bundle_cache:/bundle
    env_file:
      - ./app_variables.env
  mailcatcher:
    image: tophfr/mailcatcher
    container_name: commonfare_mailcatcher
    restart: always
    ports:
        - 1080:80
  postgres:
    image: postgres:9.6
    container_name: commonfare_pg
    restart: always
    ports:
      - "5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  swapi_commoncoin:
    image: dyne/social-wallet-api
    container_name: swapi_commoncoin
    volumes:
     - ./swapi-commoncoin-conf/social-wallet-api.yaml:/app/resources/social-wallet-api.yaml
     - ./swapi-commoncoin-conf/apikey.yaml:/app/apikey.yaml
    ports:
      - "3036:3000" # if you specify the env variable SWAPI_PORT make sure it matches the container port here
    environment:
      - SWAPI_HOST=0.0.0.0 # hostname on which the social wallet api service will listen
      # - SWAPI_PORT=4000 # port on which the social wallet api service will listen (default is 3000)
    depends_on:
      - swapi_commoncoin_mongo
    # network_mode: "host" # required if social wallet api service listens only to 'localhost'
    # These two allow debug with pry
    tty: true
    stdin_open: true
  swapi_commoncoin_mongo:
    image: mongo
    container_name: swapi_commoncoin_mongo
    volumes:
      - ./swapi-commoncoin-data/db:/data/db
    # ports:
    #   - "27017:27017" # required if social wallet api service listens only to 'localhost'
  swapi_santacoin:
    image: dyne/social-wallet-api
    container_name: swapi_santacoin
    volumes:
     - ./swapi-santacoin-conf/social-wallet-api.yaml:/app/resources/social-wallet-api.yaml
     - ./swapi-santacoin-conf/apikey.yaml:/app/apikey.yaml
    ports:
      - "3037:3000" # if you specify the env variable SWAPI_PORT make sure it matches the container port here
    environment:
      - SWAPI_HOST=0.0.0.0 # hostname on which the social wallet api service will listen
      # - SWAPI_PORT=4000 # port on which the social wallet api service will listen (default is 3000)
    depends_on:
      - swapi_santacoin_mongo
    # network_mode: "host" # required if social wallet api service listens only to 'localhost'
    # These two allow debug with pry
    tty: true
    stdin_open: true
  swapi_santacoin_mongo:
    image: mongo
    container_name: swapi_santacoin_mongo
    volumes:
      - ./swapi-santacoin-data/db:/data/db
  commonshare:
    image: commonfare/commonshare-python
    container_name: commonshare
    volumes:
     - ~/tmp/commonshare-data:/usr/src/app/data
    ports:
      - "5001:5000"
volumes:
  bundle_cache:
