# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 820f25eae1b5efd950663016695f709f87878c3033ace81eb8054cdc03865dfb2bc1e27c599081bda8caf931d495ea7f9ee5032cf47b130f9de2c7869d58f13e

test:
  secret_key_base: 70a4abad642d89c3fc7b4cae85149cd1c2f93daa065444acdd951741433788fb6b6b813822864917b91283769eb3413e4e6506e70c3aa2d6eeb28df1e995b370

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
